version: '2'

services:
  app:
    build: .

  test-app:
    build: .

    depends_on:
      - test-db

    volumes:
      - .:/just-married

    environment:
      DATABASE_URL: postgres://just_married:just_married@test-db/just_married

  test-db:
    image: postgres:9.6

    ports:
      - "5440:5432"

    environment:
      POSTGRES_USER: just_married
      POSTGRES_PASSWORD: just_married
      POSTGRES_DATABASE: just_married
