# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.7.1

    working_directory: ~/just-married

    environment:
      LEIN_ROOT: "true"
    
    steps:
      - checkout
      - run: lein test
